### ISSUE TITLE
MineOS isn't downloading

### ISSUE THREAD

**Issue by JustTheAlan** [IgorTimofeev/MineOS#647] opened 2024-11-10 17:29 UTC
when i trying to install MineOS by pastebin and wget there is a error about provider

![2024-11-10_20 26 10](https://github.com/user-attachments/assets/5ff82e80-997f-4c29-b6db-013e94971c4c)

**Comment by CoolCat467** [comment] 2024-11-10 19:16
This is a duplicate of #640, #638, #623, #619, #612, #611, #610, #600, #598, #596, #593, #592, and probably more but that's the farthest back I looked.

Please see https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue.

Basically you need to re-install a new version of Java. The version of java you are using has outdated SSL certificates that leads to this error. Installing a new version of java will have new versions of the SSL certificates, meaning error should not happen any longer.

**Closed** 2024-11-10 21:46 UTC
