### ISSUE TITLE
Program doesnt function on MC server, but works on singleplayer (continued)

### ISSUE THREAD

**Issue by cadergator10** [IgorTimofeev/MineOS#450] opened 2022-06-03 18:53 UTC
Sorry for making a new issue. Im unable to reopen my last one https://github.com/IgorTimofeev/MineOS/issues/449#issue-1259888319

I'll have to double check the path into the app if there are any invalid characters, but the 2.#.# thing is only the github folder. The folder doesn't actually exist on mineos. The app store installed the mineosdatabase.lua as Main.lua. Also, about running a server I actually mean that I have my own MC server using opencomputers to clarify just in case. I have a MineOS computer on both a singleplayer world (for testing programs) and a MineOS computer on the server I run. The program works on my singleplayer world but not the minecraft server. I only call the Filesystem a few times, and the path to the script is Applications/Security Database 2.0/ when I run system.getScriptDirectory()

**Comment by CoolCat467** [comment] 2022-06-04 01:29
![image](https://user-images.githubusercontent.com/52022020/171971320-bc46dfa8-0312-479d-9610-2d5d6c3c9ae8.png)

**Comment by IgorTimofeev** [comment] 2022-06-04 08:13
Just curious: what if numeric characters in "2.0 database..." folder name are being marked as non-valid for your system?

https://gis.stackexchange.com/questions/7886/is-starting-names-with-numbers-a-bad-data-naming-convention

**Comment by cadergator10** [comment] 2022-06-04 09:39
> Just curious: what if numeric characters in "2.0 database..." folder name are being marked as non-valid for your system?
> 
> https://gis.stackexchange.com/questions/7886/is-starting-names-with-numbers-a-bad-data-naming-convention

That could be a reason that I could verify.

**Comment by cadergator10** [comment] 2022-06-06 09:55
I've confirmed renaming the app from 2.0 security database to security database did not fix the issue

**Comment by IgorTimofeev** [comment] 2022-06-06 11:17
Sad. The essence of the problem is that the system is trying to display the file and line in which the original error occurred. The error occurs when trying to read lines using **filesystem.lines(path)**, and the path "contains invalid characters", so reading fails. Its nearly weird, because if path is invalid - files/dirs can't be even created (downloaded) using given path.

So... weird errors requires weird solutions. You can modify **Libraries/Filesystem.lua** and replace **filesystem.lines** function with this one:

```lua
function filesystem.lines(path)
	local handle, reason = filesystem.open(path, "rb")
	if handle then
		return handle:lines()
	else
		error("Unable to read lines from file: " .. tostring(reason) .. ", the path was " ..  tostring(path))
	end
end
```

At least it will give you an "invalid characters" path to fix problem

**Comment by cadergator10** [comment] 2022-06-06 21:06
It gave me two new errors:
![2022-06-06_17 04 06_2](https://user-images.githubusercontent.com/75097681/172249054-7f28c76f-814d-48e1-a2ac-f6a905927a00.png)
![2022-06-06_17 05 13_2](https://user-images.githubusercontent.com/75097681/172249141-27baf42b-7be8-41fc-96b7-93b0f8416744.png)
The 1st came right after I changed it (might not have had applied library changes yet since I didnt reboot the pc
The 2nd is the new error.

**Comment by IgorTimofeev** [comment] 2022-06-07 00:50
Wow, interesting bug, thanks for finding. There was 2 problems: 

1) The **color** library did not support explicit code source when loading optimized color processing methods for a specific CPU architecture. I.e. calling load("lua code", "=source") without second argument will set "lua code" string as source. That was fixed

2) The **system** library worked incorrectly with the errors, trying to analyze them not by the stack trace, but by debug.getinfo(), which can't process source of load("lua code", **source**) where **source** is not a file

You'll need to update these libraries, and as result this they show you some error information. I assume your sofware just have some invalid color constants in some widgets

**Comment by cadergator10** [comment] 2022-06-07 21:24
![2022-06-07_14 28 43_2](https://user-images.githubusercontent.com/75097681/172484838-fbf5ae28-0957-4104-a61e-df1d31c73237.png)
This is the error it presents now that I updated everything. I just don't know what could possibly be wrong with the program, as it works perfectly on the singleplayer world but crashes the entire pc on the multiplayer world. For this reason I don't think its an incorrect color code. It all uses 0x###### in the default.lua and works fine offline.

**Comment by cadergator10** [comment] 2022-06-07 21:25
Now that I think of it: does that mean it's a broken base file, as it is failing to read a lua53colorfunctions file. Also, I narrowed it down to where this occurs: It crashes when workspace:draw() runs.

**Comment by CoolCat467** [comment] 2022-06-08 00:24
Curious, is there any way that 

lua```
gpu.getForeground()
```
[link](https://github.com/cadergator10/opencomputer-security-system/blob/5764687831340e67ec0ef88ea25469151c7a57f5/src/server/2.%23.%23/server.lua#L88)
could ever return something invalid?

According to documentation on the gpu component at https://ocdoc.cil.li/component:gpu

```
getForeground(): number, boolean
Like getBackground, but for the foreground color.

getBackground(): number, boolean
Gets the current background color. This background color is applied to all “pixels” that get changed by other operations.
Note that the returned number is **either an RGB value in hexadecimal format, i.e. 0xRRGGBB, or a palette index**. The second returned value indicates which of the two it is (true for palette color, false for RGB value).
```

I don't know if MineOS would change this, but could it be possible that value being one or the other could cause issues?

**Comment by IgorTimofeev** [comment] 2022-06-08 01:12
> It crashes when workspace:draw() runs

Yep, it's normal behaviour when rendering some corrupted widgets. For example, if you create a **GUI.button** with **nil** color - system will be crashed with similar error in color library. In theory, I would have to do type checking when creating a button, but this entails a huge performance loss, so as part low-end OpenComputers environment, I decided to put this responsibility onto the shoulders of application software developers

**Comment by cadergator10** [comment] 2022-06-08 03:16
Ok, but then it begs the question: why does the same program work on my singleplayer world and not the multiplayer world

**Comment by IgorTimofeev** [comment] 2022-06-08 03:59
Idk bro, its fucking weird. Maybe server uses LuaJ (not Eris as it should be) and somehow some method in color library performs some invalid calculation...

**Comment by IgorTimofeev** [comment] 2022-06-08 04:07
I even don't understand why the hell it tries to read  "lua53colorfunctions" as a file, because in test environment this works fine:

1) Color lib:

![image](https://user-images.githubusercontent.com/11760002/172529308-339a8da8-0db9-40e2-b0c2-0c9a8d8378f4.png)

2) Test script

![image](https://user-images.githubusercontent.com/11760002/172529360-f12f07ad-ff65-4f8b-b262-8aed67dd61b2.png)

3) Result

![image](https://user-images.githubusercontent.com/11760002/172529404-b400ebfe-f4b4-46f9-a319-7c88686406b2.png)

**Closed** 2022-06-08 20:46 UTC

**Comment by CoolCat467** [comment] 2022-06-09 00:19
That's still weird that it works single-player, but I'm glad that's all sorted out.

**Comment by IgorTimofeev** [comment] 2022-06-09 02:06
> because of the configuration of it

![image](https://user-images.githubusercontent.com/11760002/172748793-ba4349cd-a324-4b71-bac1-5910da0c49be.png)
