### ISSUE TITLE
OpenComputers config file ignored.

### ISSUE THREAD

**Issue by osctorand** [IgorTimofeev/MineOS#327] opened 2021-03-07 20:45 UTC
MineOS ignores the 3d printing configuration, and is always limited to 24 shapes no matter what the config file says. Tried both on singleplayer and multiplayer, but the issue still persists.

**Comment by osctorand** [comment] 2021-03-07 21:17
Fixed the issue by editing the main.lua file for the 3d print application in the world folder. Still, it syas in the applications "help" tab to onlyt change the "property file", so that is misleading.

**Comment by IgorTimofeev** [comment] 2021-03-07 22:41
Yeah, it's a known issue, thanks. The program was designed to work even without 3D-printer, so default 24 shapes limit was hardcoded in [this line](https://github.com/IgorTimofeev/MineOS/blob/master/Applications/3D%20Print.app/Main.lua#L81) because of impossibility to detect server config value if printer is not attached. 

I'll have to work hard to add a dynamic number of shapes that change in real time when the printer is attaching/detaching... maybe someday

**Comment by IgorTimofeev** [comment] 2021-03-09 09:21
> All you would need to do is attempt to load the component...

Just do it in pull request if it's not "too complicated", everyone will be only happy

**Comment by IgorTimofeev** [comment] 2021-03-11 23:50
Should be fixed now. Thanks, @CoolCat467

**Closed by IgorTimofeev** 2021-03-11 23:50 UTC
Labels: <3, bug
