### ISSUE TITLE
BlueScreen after logging in 

### ISSUE THREAD

**Issue by Axor58** [IgorTimofeev/MineOS#540] opened 2023-04-22 17:27 UTC
![image](https://user-images.githubusercontent.com/75118423/233798256-8702e332-2130-47ac-8b85-dd5862ce060a.png)
 Somebody who knows how to fix it ? :D

**Comment by CoolCat467** [comment] 2023-04-22 18:28
I think I saw a similar issue to this recently, I think re-installing might help you.

**Comment by IgorTimofeev** [comment] 2023-04-23 13:13
This is a kind of "magic" error, I can't reproduce it on either lua 5.2 or 5.3 when installing a clean system. Maybe you have some specific features of the client? Which version of the game, which forge?

**Comment by IgorTimofeev** [comment] 2023-05-04 11:24
Fixed in #545, thanks <3

**Closed by IgorTimofeev** 2023-05-04 11:24 UTC
